services:
  postgres:
    image: postgres:18.1-alpine3.23
    container_name: wallet_ledger_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=wallet_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
